coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

comment:
  layout: 'diff, flags, files' # Remove items here to change the format
